### ISSUE TITLE
Broken with v1.13.0

### ISSUE THREAD

**Issue by Jakesta13** [Pugmatt/BedrockConnect#1]
Hello,
I tried to connect to the server on the new v1.13.0 release on the switch and it throws a huge error and it hangs on "connecting to server"

I'm on mobile, formatting doesn't seem to want to work for the below;

Player disconnected
Oct 31, 2019 4:01:17 PM com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler exceptionCaught
SEVERE: An exception occurred in RakNet
java.lang.IllegalStateException: No PacketCodec is set!
        at com.nukkitx.network.util.Preconditions.checkState(Preconditions.java:497)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:97)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.sendPacket(BedrockSession.java:76)
        at main.com.pyratron.pugmatt.bedrockconnect.listeners.PacketHandler.handle(PacketHandler.java:977)
        at com.pyratron.pugmatt.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:20)
        at com.pyratron.pugmatt.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:315)
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:442)
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:420)
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:408)
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:287)        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:278)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
        at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:483)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408)        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
        at java.lang.Thread.run(Thread.java:745)

Player disconnected

**Comment by Pugmatt** [comment]
Currently working on a 1.13 patch. I'll be trying to get it out in the next day or two.

**Comment by Jakesta13** [comment]
> Currently working on a 1.13 patch. I'll be trying to get it out in the next day or two.

Thanks for the effort you put into this

**Comment by crazy888** [comment]
Oh this is what I really need. Hope your are able to fix this

**Comment by jackson-57** [comment]
@crazy888 @Jakesta13 It looks like the server list has been updated!

**Comment by Pugmatt** [comment]
The official BedrockConnect server is currently updated, I have to still update the GitHub though. As of right now the 1.13 version is still a bit buggy and strange to get running v.s. the 1.12 version, but I'll probably upload the release here anyways and give you guys the instructions on how to get it running.

**Comment by mclauncherlinux** [comment]
@Pugmatt can u not just use Nukkit ? it performs pretty good and there is already a lobby plugin if u need and a transfer command too

**Comment by Jakesta13** [comment]
> @Pugmatt can u not just use Nukkit ? it performs pretty good and there is already a lobby plugin if u need and a transfer command too

This isn't a full sever software, it's only purpose is to give you freedom to connect to different servers on something like the Switch edition, instead of having to change your DNS spoof all the time.

**Comment by Pugmatt** [comment]
> @Pugmatt can u not just use Nukkit ? it performs pretty good and there is already a lobby plugin if u need and a transfer command too

I could, but it would use a lot more resources than needed. All that's needed with this software is to load a UI, so limiting the packets to just the UI and transfer packets and nothing else makes the server lightweight to host.

**Comment by Pugmatt** [comment]
Sorry for the long wait guys, here's the 1.13 patch. I patched up the stability issues so it should run like normal with the instructions in the README. https://github.com/Pugmatt/BedrockConnect/releases/tag/1.2
