### ISSUE TITLE
No PacketCodec is set!

### ISSUE THREAD

**Issue by bile0026** [Pugmatt/BedrockConnect#109]
Looks like this is happening on 1.16.101.01. Seems to be the same issue as #1 and #27 

This error occurs as soon as any device tries to connect to my private bedrock connect service.

```
[Network Listener - #1] ERROR com.nukkitx.network.raknet.RakNetServer - An exception occurred in RakNet
sh[95682]: java.lang.IllegalStateException: No PacketCodec is set!
sh[95682]:         at com.nukkitx.network.util.Preconditions.checkState(Preconditions.java:497)
sh[95682]:         at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:99)
sh[95682]:         at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.sendPacket(BedrockSession.java:78)
sh[95682]:         at main.com.pyratron.pugmatt.bedrockconnect.listeners.PacketHandler.handle(PacketHandler.java:1172)
sh[95682]:         at com.pyratron.pugmatt.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:21)
sh[95682]:         at com.pyratron.pugmatt.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:26)
sh[95682]:         at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:271)
sh[95682]:         at com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:32)
sh[95682]:         at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:307)
sh[95682]:         at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:434)
sh[95682]:         at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:412)
sh[95682]:         at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:400)
sh[95682]:         at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:279)
sh[95682]:         at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
sh[95682]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
sh[95682]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
sh[95682]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
sh[95682]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
sh[95682]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
sh[95682]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
sh[95682]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
sh[95682]:         at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:513)
sh[95682]:         at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$1.run(AbstractEpollChannel.java:385)
sh[95682]:         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
sh[95682]:         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
sh[95682]:         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:338)
sh[95682]:         at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
sh[95682]:         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
sh[95682]:         at java.base/java.lang.Thread.run(Thread.java:834)
sh[95682]: null disconnected
```

**Comment by Pugmatt** [comment]
Not currently able to replicate this on my end, and the 1.16.101.01 update for the Switch has been out since the 24th and this is the first I've heard of this happening since that update.

Just to confirm, you are using this version, correct? - https://github.com/Pugmatt/BedrockConnect/releases/tag/1.5.5

**Comment by bile0026** [comment]
No, I just realized I was running an old version. Upgraded to 1.5.5 and everything is working as expected. 

Maybe a suggestion, spit out the current version in the logs when starting the jar file? Might make it easier to see that kind of issue down the road. 

Thank you for the response!
