### ISSUE TITLE
Error when running 

### ISSUE THREAD

**Issue by smooreace** [Pugmatt/BedrockConnect#210]
I get the following when I try running this. Systems is a Server 2016 environment currently running both bedrock and java Minecraft server, among a dozen or so other game servers sitting on a static IP. 

`Loaded 0 custom servers
java.util.concurrent.CompletionException: java.net.BindException: Address already in use: bind
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1494)
        at java.base/java.util.concurrent.CompletableFuture.unipush(CompletableFuture.java:589)
        at java.base/java.util.concurrent.CompletableFuture.bipush(CompletableFuture.java:1243)
        at java.base/java.util.concurrent.CompletableFuture.andTree(CompletableFuture.java:1518)
        at java.base/java.util.concurrent.CompletableFuture.allOf(CompletableFuture.java:2415)
        at com.nukkitx.network.util.Bootstraps.allOf(Bootstraps.java:118)
        at com.nukkitx.network.raknet.RakNetServer.bindInternal(RakNetServer.java:81)
        at com.nukkitx.network.raknet.RakNet.bind(RakNet.java:43)
        at com.pyratron.pugmatt.protocol.bedrock.Bedrock.bind(Bedrock.java:35)
        at main.com.pyratron.pugmatt.bedrockconnect.Server.<init>(Server.java:83)
        at main.com.pyratron.pugmatt.bedrockconnect.BedrockConnect.main(BedrockConnect.java:197)
Caused by: java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:552)
        at java.base/sun.nio.ch.DatagramChannelImpl.bindInternal(DatagramChannelImpl.java:1189)
        at java.base/sun.nio.ch.DatagramChannelImpl.bind(DatagramChannelImpl.java:1160)
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:125)
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:122)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
        at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:122)
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:199)
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:194)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:831)`

**Comment by Pugmatt** [comment]
The error would imply that there is another program that is binded to port 19132, which is the port that BedrockConnect needs to run on.

Keep in mind if your bedrock game server is using the official server software, it will always claim port 19132, even if you have the configuration file set to bind to a different port. (Currently a bug that from what I'm aware of, has not been fixed yet https://bugs.mojang.com/browse/BDS-3989) If this is the case, you would either need to host the two servers on different environments, or use a 3rd party bedrock game server software like Nukkit that wouldn't force-bind 19132.

**Comment by smooreace** [comment]
So this tool is also launching the server? I saw the initial error about the "Address already in use", but never saw it was running the server too. I have a server manager to deal with that side of things

**Comment by Pugmatt** [comment]
I'm unsure what you mean. BedrockConnect just runs BedrockConnect, which is a server that runs on port 19132. Players connect to this which launches the serverlist interface.

**Comment by smooreace** [comment]
OK.. so if the server is already running on the same machine then the port
is clearly already in use. So is bedrock connect is intended to be ran on a
different machine?

**Comment by Pugmatt** [comment]
As said in my original reply, due to the bug with the official bedrock server software already claiming port 19132, yes it would need to be ran on a different machine. This isn't BedrockConnect's intention but it needs to done because of the bug with Mojang's server software. Or you can use a 3rd-party bedrock server software like Nukkit, which from what I believe won't claim port 19132 if you specify it to. 

BedrockConnect needs to be on port 19132, in order for the DNS bypass trick to work.

**Comment by smooreace** [comment]
Im sorry. I guess I wasnt as awake when I read that comment as I thought I was! I totally get it now. Ill just move BedrockConnect to my web server and rock on. Thanks for your time!
