### ISSUE TITLE
Broken from v1.14.60

### ISSUE THREAD

**Issue by nwam** [Pugmatt/BedrockConnect#27]
When connecting to BedrockConnect in Switch. Here is the stack trace:
```
Bedrock Connection Started: localhost:19132
Apr 15, 2020 8:18:37 PM com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler exceptionCaught
SEVERE: An exception occurred in RakNet
java.lang.IllegalStateException: No PacketCodec is set!
        at com.nukkitx.network.util.Preconditions.checkState(Preconditions.java:497)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.checkPacket(BedrockSession.java:97)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.sendPacket(BedrockSession.java:76)
        at main.com.pyratron.pugmatt.bedrockconnect.listeners.PacketHandler.handle(PacketHandler.java:1157)
        at com.pyratron.pugmatt.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:16)
        at com.pyratron.pugmatt.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:22)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:278)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28)
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:301)
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:428)
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:406)
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:394)
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:273)
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Unknown Source)

null disconnected
```

**Comment by nwam** [comment]
Seems similar to #1

**Comment by Pugmatt** [comment]
Yeah, this is from the new update. Currently working on updating everything.

**Comment by Pugmatt** [comment]
Push is now live, should be working now on 1.14.60. Let me know if any issues arise: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.4.2

**Comment by GeertvanDrunen** [comment]
> Push is now live, should be working now on 1.14.60. Let me know if any issues arise: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.4.2

Works perfectly, thanks a lot man!
