### ISSUE TITLE
Hello! I'm Japanese.

### ISSUE THREAD

**Issue by koaf** [Pugmatt/BedrockConnect#270]
I am Japanese, and I used Bedrockconnect.
My friend also used it, but I don't understand English, so I did my best to translate it for him.
Can I publish this DNS?

**Comment by CrafterPika** [comment]
Bedrock connect has an option to change the language of the server list https://github.com/Pugmatt/BedrockConnect#change-wording-of-serverlist, for DNS Depending on your OS.

**Comment by Pugmatt** [comment]
Hello! If by publish DNS you mean adding it to the list of instances in the README, yes this can be done if you want to reply with the IP of the DNS.

**Comment by koaf** [comment]
We have a new problem.
I used install-bind.sh, but it didn't work.
What should I do?

**Comment by CrafterPika** [comment]
> I used install-bind.sh, but it didn't work.
What should I do?
what is your linux distro,
can you show a picture of the error

**Comment by koaf** [comment]
The OS is Ubuntu.
It looks like this, though I used Install.sh
https://media.discordapp.net/attachments/924619659846774796/940510326456217640/IMG_0506.jpg?width=565&height=754

**Comment by CrafterPika** [comment]
from the translated error, it seems like you entered the wrong dns info, ensure your primary is your bedrock instance ip, anf the secondary is something like 1.1.1.1 or 8.8.8.8

**Comment by koaf** [comment]
Sorry, another error. I got this log when I started it.
java.util.concurrent.CompletionException: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: アドレスは既に使用中です
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498)
        at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at com.nukkitx.network.util.Bootstraps.lambda$allOf$0(Bootstraps.java:111)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:1017)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:564)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: アドレスは既に使用中です

**Comment by Pugmatt** [comment]
The error implies there is another software/process running on your machine using the same port, 19132. Keep in mind if you're also running a Minecraft game server on the same machine, you'll need to change the port of the Minecraft game server. DON'T change the port of BedrockConnect, as it needs to be on port 19132 to work correctly.

**Comment by koaf** [comment]
OK.
