### ISSUE TITLE
Exception raise after 1.19 update

### ISSUE THREAD

**Issue by meisjohn** [Pugmatt/BedrockConnect#304]
### What happened?

I just updated my phone and my Bedrock Connect container to 1.19 (using the same procedure I've used for other updates successfully) and i'm receiving the following exception when I try to connect from my phone:

```
Bedrock Connection Started: 0.0.0.0:19132
[Network Listener - #3] WARN io.netty.util.concurrent.AbstractEventExecutor - A task raised an exception. Task: com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener$$Lambda$155/0x00000008402aa440@7d5356ca
 java.lang.NullPointerException: packetCodec
 	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
 	at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.setPacketCodec(BedrockSession.java:81)
 	at main.com.pyratron.pugmatt.bedrockconnect.listeners.PacketHandler.handle(PacketHandler.java:485)
 	at com.pyratron.pugmatt.protocol.bedrock.packet.LoginPacket.handle(LoginPacket.java:21)
 	at com.pyratron.pugmatt.protocol.bedrock.handler.DefaultBatchHandler.handle(DefaultBatchHandler.java:29)
 	at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:284)
 	at com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener.lambda$onEncapsulated$0(BedrockRakNetSessionListener.java:39)
 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 	at java.base/java.lang.Thread.run(Thread.java:829)
 null disconnected

```
 

Also attempted to pull the latest version of the repository from GitHub and build the JAR file manually, receiving the same result (after updating the Dockerfile to point to the locally built copy of the JAR instead of pulling from Github.)

### Excepted Behaviour?

Expect to be able to connect to the server and be presented with my server list.

### Steps to reproduce.

1. Update Client and BedrockConnect server to Minecraft 1.19
2. Attempt to connect from the client to the server
3. Observe exception in the logs in the server and "Could not connect: Outdated Server" error on the client. 

### Minecraft Bedrock Version

1.19

### Console

Mobile (Version 1.19.0.5) and Nintendo Switch (1.19.1)

**Comment by meisjohn** [comment]
Note, it does still work when connecting from a PC still running Minecraft Bedrock 1.18.31

**Comment by meisjohn** [comment]
Disregard, I missed a step in my procedure. Sorry.

**Comment by AidanWright** [comment]
Sorry to open a closed issue, but what was the step you missed?  I'm having the same exception `java.lang.NullPointerException: packetCodec`, but am unable to figure out what I did wrong. Thanks.

**Comment by meisjohn** [comment]
Aidan,  

I have the BedrockConnect instance running in a Docker Container and the internal volume was keeping the 1.18.30 JAR file, I had to go into the volume and remove the old JAR, replacing it with the 1.19 compatible JAR for it to work right. 

I hope this helps.  
John.

**Comment by AidanWright** [comment]
Wow can't believe I didn't catch that. I was able to get it to work now. Thank you
