### ISSUE TITLE
Java error in self-hosted JSON config file

### ISSUE THREAD

**Issue by WombleWoo7547** [Pugmatt/BedrockConnect#356]
### What happened?

I started the self-hosted server and saw the starter things, player limit, port all that but then I got the error:
`java.lang.NullPointerException: Cannot invoke "java.lang.Long.intValue()" because the return value of "org.json.simple.JSONObject.get(Object)" is null
	at main.com.pyratron.pugmatt.bedrockconnect.CustomServerHandler.createServer(CustomServerHandler.java:62)
	at main.com.pyratron.pugmatt.bedrockconnect.CustomServerHandler.initialize(CustomServerHandler.java:42)
	at main.com.pyratron.pugmatt.bedrockconnect.BedrockConnect.main(BedrockConnect.java:158)`
and saw my zsh prompt again. 

### Expected Behaviour?

I saw the "Bedrock connect started" message and the BedrockConnect server appeared in my LAN games in my Minecraft.

### Steps to reproduce.

N/A

### Screenshots/Videos

N/A

### Minecraft Bedrock Version

1.19.50

### Console

Xbox One S

### Additional Context

Fresh install, straight from download .zip file, checksums matched.

**Comment by WombleWoo7547** [comment]
(Here is my config file) - https://pastebin.com/raw/7KuB2JKx

**Comment by WombleWoo7547** [comment]
@Pugmatt

**Comment by CrafterPika** [comment]
> (Here is my config file) - https://pastebin.com/raw/7KuB2JKx

```json
      {
        "name": "Zeqa",
        "iconUrl": "https://dunb17ur4ymx4.cloudfront.net/webstore/logos/f136bb5045f9a75671767007ad12441d728c8556.png",
        "address": "zeqa.net"
      }
```

here is the issue no port specified. [Looking](https://github.com/Pugmatt/BedrockConnect/blob/master/serverlist-server/src/main/com/pyratron/pugmatt/bedrockconnect/CustomServerHandler.java#L62) at the actual code, the error occurs when trying to parse for the "port" value.

[i corrected for you](https://pastebin.com/raw/xJUQyE7P)
