### ISSUE TITLE
Language file does not apply

### ISSUE THREAD

**Issue by Lovingtaken3** [Pugmatt/BedrockConnect#492]
### What happened?

When I start the server,  get "Unexpected token END OF FILE at position 2284.
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:257)
        at org.json.simple.parser.JSONParser.parse(JSONParser.java:92)
        at main.com.pyratron.pugmatt.bedrockconnect.config.Language.loadCustom(Language.java:64)
        at main.com.pyratron.pugmatt.bedrockconnect.config.Language.<init>(Language.java:35)
        at main.com.pyratron.pugmatt.bedrockconnect.BedrockConnect.main(BedrockConnect.java:191)
- MySQL Connection Started -
Bedrock Connection Started: 0.0.0.0:19132" and the server does start up fine, but I want it to use my language file

### Expected Behaviour?

Language file should apply and players should see it in the game.

### Minecraft Bedrock Version

latest

### Console

All

**Comment by Pugmatt** [comment]
Could you provide the contents of your language file? Sounds like a possible syntax/formatting error in the file.
