### ISSUE TITLE
Exception in thread "main" java.lang.AssertionError: java.lang.NullPointerException: stream

### ISSUE THREAD

**Issue by Ma110w** [Pugmatt/BedrockConnect#534]
### What happened?

Completely Inability To Launch Bedrock Connect Server

### Expected Behaviour?

Bedrock Connect Server Correctly Starts up and does not produce a error

### Steps to reproduce.

Open Bedrock Connect

### Screenshots/Videos

![image](https://github.com/user-attachments/assets/896d94cc-e1f6-444a-bdef-e71d4dce0619)

### Minecraft Bedrock Version

1.21.20

### Console

N/A

### Additional Context

"-= BedrockConnect (Release: 1.45) =-
Exception in thread "main" java.lang.AssertionError: java.lang.NullPointerException: stream
        at main.com.pyratron.pugmatt.bedrockconnect.utils.PaletteManager.<clinit>(PaletteManager.java:42)
        at main.com.pyratron.pugmatt.bedrockconnect.BedrockConnect.main(BedrockConnect.java:54)
Caused by: java.lang.NullPointerException: stream
        at java.base/java.util.Objects.requireNonNull(Objects.java:246)
        at org.cloudburstmc.nbt.NbtUtils.createNetworkReader(NbtUtils.java:54)
        at org.cloudburstmc.nbt.NbtUtils.createNetworkReader(NbtUtils.java:87)
        at org.cloudburstmc.nbt.NbtUtils.createNetworkReader(NbtUtils.java:83)
        at main.com.pyratron.pugmatt.bedrockconnect.utils.PaletteManager.<clinit>(PaletteManager.java:38)
        ... 1 more" 
# On Windows 11 23H2

**Comment by Pugmatt** [comment]
According to the release number in the first line of the log, you are using version 1.45, the current version is 1.49 so you are using an out of date version of the software. (As that version won't work with Minecraft 1.21.20 anyway) Update your BedrockConnect jar to the latest under [Releases](https://github.com/Pugmatt/BedrockConnect/releases) and see if that fixes it.

**Comment by Ma110w** [comment]
> According to the release number in the first line of the log, you are using version 1.45, the current version is 1.49 so you are using an out of date version of the software. (As that version won't work with Minecraft 1.21.20 anyway) Update your BedrockConnect jar to the latest under [Releases](https://github.com/Pugmatt/BedrockConnect/releases) and see if that fixes it.

Not contesting this, just it sounds odd, i have only learned that your project existed 3-4 days ago, im unsure how i have such a outdated version?

**Comment by Pugmatt** [comment]
I'm not really sure either, I checked and the latest release files and they are up to date.

Where did you download the BedrockConnect jar originally? I know there's some 3rd-party Docker images and software out there not associated with this project that attempt to bundle BedrockConnect. Those tend to sometimes serve outdated versions. Also possible you followed a link from a tutorial that has the 1.45 version linked directly such as https://github.com/Pugmatt/BedrockConnect/releases/tag/1.45

**Comment by Ma110w** [comment]
Funnily enough, I found your project's GitHub page through a Google search. I literally searched "minecraft bedrock custom servers", and your GitHub was the first or second link that came up. On the first of this month.

**Comment by Ma110w** [comment]
alright, now this is really weird, I did a fresh install and its still saying exactly the same thing, down to the version number,

https://github.com/user-attachments/assets/09779adc-6463-4ff3-9ad8-f94811f79d4b

**Comment by Ma110w** [comment]
i have so many installed im unsure where all of them are, im gonna try and find a tool, or write one

**Comment by Ma110w** [comment]
OH AND ALSO, i was wrong earlier, after the fresh install, what i didn't realize was the version swapped from 1.45 to 1.49, but still produced the same or similar error 
![image](https://github.com/user-attachments/assets/461aa561-2dc6-4a91-b1b5-3ff9e0cb0ecf)

**Comment by Ma110w** [comment]
did i say something wrong?

**Comment by Pugmatt** [comment]
Sorry I haven't had time lately to review this too deeply. From the time I've had I haven't been able to replicate the issue unfortunately upon many attempts to match the environment. Only other possible anomaly I could see is maybe the storage device you are attempting to run BedrockConnect off of, Samsung Drive it looks like in the screen video. If you haven't already try moving it to a different drive like your C or D drive and see if that changes anything?
