### ISSUE TITLE
Failed to run jar, returns "Address already in use: bind"

### ISSUE THREAD

**Issue by JacobTyBruce** [Pugmatt/BedrockConnect#76]
I am trying to run the jar file to set up my own server, but when I run the jar file I get this
```
java.util.concurrent.CompletionException: java.net.BindException: Address already in use: bind
        at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
        at java.util.concurrent.CompletableFuture.biRelay(Unknown Source)
        at java.util.concurrent.CompletableFuture$BiRelay.tryFire(Unknown Source)
        at java.util.concurrent.CompletableFuture.andTree(Unknown Source)
        at java.util.concurrent.CompletableFuture.allOf(Unknown Source)
        at com.nukkitx.network.util.Bootstraps.allOf(Bootstraps.java:118)
        at com.nukkitx.network.raknet.RakNetServer.bindInternal(RakNetServer.java:64)
        at com.nukkitx.network.raknet.RakNet.bind(RakNet.java:50)
        at com.pyratron.pugmatt.protocol.bedrock.Bedrock.bind(Bedrock.java:33)
        at main.com.pyratron.pugmatt.bedrockconnect.Server.<init>(Server.java:109)
        at main.com.pyratron.pugmatt.bedrockconnect.BedrockConnect.main(BedrockConnect.java:235)
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.DatagramChannelImpl.bind(Unknown Source)
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:125)
        at io.netty.util.internal.SocketUtils$6.run(SocketUtils.java:122)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.bind(SocketUtils.java:122)
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind0(NioDatagramChannel.java:199)
        at io.netty.channel.socket.nio.NioDatagramChannel.doBind(NioDatagramChannel.java:194)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Unknown Source)
```
I have other Portforwards setup for Java but they don't use the same port so it shouldn't conflict, any help?

**Comment by JacobTyBruce** [comment]
Fixed, had another java process running on same port. Killed it and ran and worked fine
