### ISSUE TITLE
1.16 Release compiled from source code gives off RakNet error.

### ISSUE THREAD

**Issue by reelpufferfish** [Pugmatt/BedrockConnect#78]
If a player attempts to join the server list, this happens:

```Aug 10, 2020 9:31:05 AM com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler exceptionCaught
SEVERE: An exception occurred in RakNet
java.lang.RuntimeException: Unable to inflate buffer data
        at com.pyratron.pugmatt.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:83)
        at com.pyratron.pugmatt.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:19)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockSession.onWrappedPacket(BedrockSession.java:277)
        at com.pyratron.pugmatt.protocol.bedrock.BedrockRakNetSessionListener.onEncapsulated(BedrockRakNetSessionListener.java:28)
        at com.nukkitx.network.raknet.RakNetSession.onEncapsulatedInternal(RakNetSession.java:301)
        at com.nukkitx.network.raknet.RakNetSession.onOrderedReceived(RakNetSession.java:428)
        at com.nukkitx.network.raknet.RakNetSession.checkForOrdered(RakNetSession.java:406)
        at com.nukkitx.network.raknet.RakNetSession.onRakNetDatagram(RakNetSession.java:394)
        at com.nukkitx.network.raknet.RakNetSession.onDatagram(RakNetSession.java:273)
        at com.nukkitx.network.raknet.RakNetServer$ServerDatagramHandler.channelRead(RakNetServer.java:288)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.util.zip.DataFormatException: No zlib header
        at com.pyratron.pugmatt.protocol.util.Zlib.inflate(Zlib.java:32)
        at com.pyratron.pugmatt.protocol.bedrock.compressionhandler.DefaultBedrockCompressionHandler.decompressPackets(DefaultBedrockCompressionHandler.java:64)
        ... 24 more

**Comment by DoctorMacc** [comment]
I can confirm this.

**Comment by Pugmatt** [comment]
Does this error occur no matter what platform you join with? Or is happening with only certain platforms. 

Also by your title, is this compiled yourself or from the "Releases" section?

**Comment by reelpufferfish** [comment]
This error occurs no matter what platform a player joins from.

I've compiled from the source code in this archive from the release "1.16 Support": https://github.com/Pugmatt/BedrockConnect/archive/1.5.zip
![image](https://user-images.githubusercontent.com/61335368/89912017-b3303300-dbb7-11ea-8286-b25eb5becfe5.png)

**Comment by Pugmatt** [comment]
The source code zip in the releases doesn't match the current 1.16 master branch. I've submitted a new release that should now have the updated Source code, try this one: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.5.1

**Comment by reelpufferfish** [comment]
![image](https://user-images.githubusercontent.com/61335368/90417765-cfc9e080-e079-11ea-9805-ecc5c6e8c801.png)

**Comment by Pugmatt** [comment]
Try this one: https://github.com/Pugmatt/BedrockConnect/releases/tag/1.5.3

The DNS packages were from an unfinished DNS server prototype, so I've reverted those changes for now in the 1.5.3 release.
